### ISSUE TITLE
PyPy seems to lose its advantage at larger fields

### ISSUE THREAD

**Issue by oskar-skog-after8** [oskar-skog/anonymine#24]
PyPy seems to lose its advantage at larger fields.

CPython becomes equally fast or even faster when the fields get larger.
Extensive research should be made.

**Comment by oskar-skog** [comment]
Looks like a statistical illusion.

Tests show that PyPy performs better with average time and maximum observed time.
Tests for the median time are inconclusive.
It appears that PyPy has a narrower spread of time, giving CPython a lead with the minimum observed time, but otherwise it's faster.

**Comment by oskar-skog** [comment]
Median is also lower on PyPy.  It was just a bug in the analysis tool.

**Comment by oskar-skog** [comment]
PyPy does seem to lose some of its relative power.  But the data is insufficient, the fields are ridiculously large (larger than 500@50x50).
